name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./album-viewer
          file: ./album-viewer/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/gh-copilot-demo/album-viewer:latest
            ghcr.io/${{ github.repository_owner }}/gh-copilot-demo/album-viewer:${{ github.sha }}

      - name: Run tests
        working-directory: ./album-viewer
        run: |
          npm ci
          npm test
        env:
          NODE_ENV: test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            ./album-viewer/test-results
            ./album-viewer/coverage